from __future__ import annotations

from pathlib import Path
from typing import Literal

import numpy as np

MaterialStyle = Literal["generic", "bambu_simple"]


def _material_name(index: int, style: MaterialStyle = "generic") -> str:
    if style == "bambu_simple":
        return f"mat_{index + 1}"
    return f"Material_{index + 1:02d}"


def _write_mtl(path: Path, palette: np.ndarray, style: MaterialStyle = "generic") -> None:
    lines = ["# Generated by paint-to-print-3d", ""]
    for index, color in enumerate(np.asarray(palette, dtype=np.uint8)):
        name = _material_name(index, style=style)
        r, g, b = (float(color[0]) / 255.0, float(color[1]) / 255.0, float(color[2]) / 255.0)
        if style == "bambu_simple":
            lines.extend(
                [
                    f"newmtl {name}",
                    "Ns 32.000000",
                    "Ka 1.000000 1.000000 1.000000",
                    f"Kd {r:.6f} {g:.6f} {b:.6f}",
                    "Ks 0.500000 0.500000 0.500000",
                    "d 1.000000",
                    "illum 1",
                    "",
                ]
            )
        else:
            lines.extend(
                [
                    f"newmtl {name}",
                    "Ns 250.000000",
                    "Ka 1.000000 1.000000 1.000000",
                    f"Kd {r:.6f} {g:.6f} {b:.6f}",
                    "Ks 0.500000 0.500000 0.500000",
                    "Ke 0.000000 0.000000 0.000000",
                    "Ni 1.500000",
                    "d 1.000000",
                    "illum 2",
                    "",
                ]
            )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_grouped_obj_with_mtl(
    obj_path: str | Path,
    positions: np.ndarray,
    faces: np.ndarray,
    face_labels: np.ndarray,
    palette: np.ndarray,
    material_style: MaterialStyle = "generic",
) -> tuple[Path, Path]:
    output_path = Path(obj_path).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    mtl_path = output_path.with_suffix(".mtl")
    _write_mtl(mtl_path, palette, style=material_style)

    lines = [
        "# Generated by paint-to-print-3d",
        f"mtllib {mtl_path.name}",
        "o RegionGroupedMesh",
        "",
    ]
    for vertex in np.asarray(positions, dtype=np.float32):
        lines.append(f"v {float(vertex[0]):.6f} {float(vertex[1]):.6f} {float(vertex[2]):.6f}")

    for material_index in range(len(palette)):
        lines.extend(["", f"usemtl {_material_name(material_index, style=material_style)}"])
        for face_index, label in enumerate(np.asarray(face_labels, dtype=np.int32)):
            if int(label) != material_index:
                continue
            face = np.asarray(faces[face_index], dtype=np.int64)
            lines.append(f"f {int(face[0]) + 1} {int(face[1]) + 1} {int(face[2]) + 1}")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path, mtl_path


def write_bambu_compatible_grouped_obj_with_mtl(
    obj_path: str | Path,
    positions: np.ndarray,
    faces: np.ndarray,
    face_labels: np.ndarray,
    palette: np.ndarray,
) -> tuple[Path, Path]:
    return write_grouped_obj_with_mtl(
        obj_path,
        positions,
        faces,
        face_labels,
        palette,
        material_style="bambu_simple",
    )
